package Lec_21;

public class Keypad_Phone {
//	https://leetcode.com/problems/letter-combinations-of-a-phone-number/description/
	
//	10 size ka array bna diya....0-9 tak ki indexing..har key pe kya string likha hai uspe ek index se map kar diya...
//	0 and 1 pe kuch nahi toh blank chor diya...2 pe abc and so on. Ek static array bna liya jise ham direct use kar lenge.
//	Kon se button pe kya likha hai ye info aa gya
	static String[] key = {"", "", "abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wxyz" };
	public static void main(String[] args) {
		// TODO Auto-generated method stub
//		suppose 234 hai 3 button hai...pehle 0th button ke bare m sochna hai..0 ke corresponding character nikalenge...2 ayega...
//		Toh 2 as a character ayega na..iski ASCII value 50 hoti hai...hame 2 as a numeric chahiye hoga...
		String ques = "23"; //123
		print(ques, ""); //ques wali string, and ans wali string...
		
	}
	
	public static void print(String ques, String ans) {
//		base case
		if(ques.length()==0) {
			System.out.println(ans + " ");
			return;
		}
		
//		Jo abc hamare paas aya tha...us abc....
//		23 aya...toh 2 as a character nikal liya....use no. bna liya...uske corresponding string nikal liya abc...ab jitni iski(abc) length...utni call...
//		jo bhi ques mila hai uska sabse pehle 0th character pta karenge....
		char ch = ques.charAt(0); //isse 2 as a character milega....nikal liya 2 as a character
//		String press = key[ch]; //ye nahi karna hai...❌...isse array se abc nahi milega...ye index out of bound ho jayega cuz upar jo character nikala uski ASCII value 50 yha ayegi..and hame 2 ko as a numeric bnana hai...
//		2 ke corresponding string nikal liya...abc aa gya. 
		String press = key[ch-48]; //0 ki ASCII value - ki 48 m se. Toh 50 - 48 = 2.....2 ke corresponding string abc aa gya...
		for(int i = 0; i<press.length(); i++) { //Sabse pehle press m abc aya iski length 3 hai toh 3 baar chalega..abc ki length 3 hai toh 3 baar chalega...
//			jitni iski length utni choice...
//			question sab jagah yahi paas hoga...ek baar a ke liye, ek baar b ke liye, ek baar c ke liye...sabke ke liye 1 by 1 call jayegi...
//			and remaining string kaise nikalenge....suppose abcde m a ke alawa remaining string nikalna hota toh substring(1) karte the....
//			jitni press ki length hai utni choice hai..isliye loop lagaya hai
			print(ques.substring(1), ans+press.charAt(i)); // ans m press.charAt(i) add kar denge...ques m ques.substring(1) pass karte hai..
			
		}
	}
}
